site_name:           DynAssMgmt
repo_url:            https://github.com/JuliaFinMetriX/DynAssMgmt.jl
site_description:    First draft of a Julia implementation
site_author:         Christian Groll
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Types:
  - Return data: types/dataTypes.md
  - Moment estimators: types/estimatorTypes.md
  - Asset moments: types/universeTypes.md
  - Strategies: types/strategies.md
  - Investments: types/investmentTypes.md
  - Performance: types/bktestTypes.md
